load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "garage",
    srcs = [
        "channel/channel.cpp",
        "coroutine/coroutine.cpp",
    ],
    hdrs = [
        "channel/channel.h",
        "coroutine/coroutine.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
